


# Permalinks
permalink:        pretty

# Setup
title:            CITE data exchange
tagline:          'Open data in simple structured formats'
description:      ''


baseurl: '/citedx/'


author:
  name:           'Neel Smith'


links:
  - title: Current specification
    url: CEX-spec-3.0.1
  - title:  Github repository
    url:  https://github.com/cite-architecture/citedx
    external: true
